name: build

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: latest
      - name: install
        run: |
          npm i
      - name: ci
        run: |
          npm run ci
