name: build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: ci
        run: |
          npm install
          npm run ci
      - name: coverall
        if: success()
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
